modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="icerailhelper"
version="0.1"
displayName="Ice Rail Helper"
logoFile="logo.png"
credits="To my wife, for leading us on fun adventures in Minecraft!"
authors="Sarsk"
description='''
Add North/South/East/West alignment for straight travel on ice roads.
'''
[[dependencies.icerailhelper]] #optional
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.icerailhelper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"